### PR TITLE
Generic segment

### PR DESCRIPTION
**Pull request by JordanMartinez**
I went through your code and cleaned up some of the issues my IDE found.

I'll continue any conversation about the generic approach on the PR thread instead of here.

### CODE REVIEW

**Comment by afester** [comment]
Thanks a lot! I have merged your code into the genericSegment branch and currently checking how I can leverage that approach - just to be sure (I am not completely familiar with the `Either` generic class): To implement the segment operations for a segment which is either a StyledText or some custom object, as proposed by @TomasMikula, I would need to do something like

```
public class StyledTextOrCustomObjectOps<S> implements SegmentOps<Either<StyledText<S>, CustomObject<S>>, S>{

    private StyledTextOps<S> styledTextOps = new StyledTextOps<>();

    @Override
    public int length(Either<StyledText<S>, CustomObject<S>> seg) {
        if (seg.isLeft()) {
            return styledTextOps.length(seg.getLeft());
        } else {
            return 1;
        }
    }

 ...

```

correct?

**Comment by TomasMikula** [comment]
Correct, possibly even more generic:

``` java
public static <L, R, S> SegmentOps<Either<L, R>, S> eitherOps(lOps: SegmentOps<L, S>, rOps: SegmentOps<R, S>) {
    return new SegmentOps<Either<L, R>, S>() {

        @Override
        public int length(Either<L, R> seg) {
            if (seg.isLeft()) {
                return lOps.length(seg.getLeft());
            } else {
                return rOps.length(seg.getRight());
            }
        }

    }
}
```

**Comment by afester** [comment]
I have updated the genericSegment branch with the NodeFactory which can now be passed to the StyledTextArea. I have also started to update the RichText demo to show how to support other objects than StyledText - the model part is complete, but the creation of the JavaFX nodes is still pending. Also, still the Unit tests and the other demo applications do not compile yet.

**Comment by JordanMartinez** [comment]
Sounds good! But did you mean to say this in this PR or the one you're submitting to Tomas?

**Comment by afester** [comment]
I was probably mislead by your comment above, "continue any conversation about the generic approach on the PR thread instead of here." - I did not find any other PR thread though :laughing:
Anyway, I just refreshed the code on the PR on Tomas' repository...

**Comment by JordanMartinez** [comment]
Oh sorry! I meant let's continue any conversion we may have on the PR you
submitted to Tomas and not this PR.

**Pull request closed without merging**
